global:
  scrape_interval: 5s
  external_labels:
    site: prod

# VictoriaMetrics Storage: 
remote_write:
  - url: http://192.168.0.102:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30

rule_files:
  # - "alert.rules.yml"
  - "services.rules.yml"
  - "critical.rules.yml"
  - "warning.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.0.102:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.102:9090']

  - job_name: 'node_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.104:9100']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['192.168.0.102:8428']

  - job_name: 'mysql_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.0.104:9104']

  - job_name: 'Blackbox-ICMP'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.d/blackbox-icmp.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.104:9115

  - job_name: 'Blackbox-TCP'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.d/blackbox-tcp.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.104:9115

  - job_name: 'Blackbox-HTTP'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.d/blackbox-http.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.104:9115
